MAILCHIMP_API_KEY: "2dbfa585b912764ae2fa8c749f1523f5-us15"
MAILCHIMP_LIST_NEWSLETTER: "e570ab2d2b"

development:
  ASSET_HOST: "http://localhost:3000"

staging:
  HOST: "https://maisonmineralogie-staging.herokuapp.com"


production:
  HOST: "https://maisonmineralogie-production.herokuapp.com"

