meta_title: "MMC - Maison de la Minéralogie de Chalabre"
meta_description: "La planète cristalline révélée dans ses formes les plus créatives"
meta_image: "meta/meta_image.jpg" # Une image dans votre dossier app/assets/images/
